# Generated by Django 6.0.3 on 2026-03-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(default='context_exposure', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_prompt', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('roleplay', 'Roleplay'), ('obfuscated', 'Obfuscated')], max_length=50)),
                ('template_text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_rate', models.FloatField(default=0.0)),
                ('exact_leak_rate', models.FloatField(default=0.0)),
                ('partial_leak_rate', models.FloatField(default=0.0)),
                ('semantic_leak_rate', models.FloatField(default=0.0)),
                ('overall_risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Low', max_length=50)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_text', models.TextField()),
                ('latency', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.experiment')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generatedprompt')),
            ],
        ),
        migrations.CreateModel(
            name='LeakageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('leakage_type', models.CharField(choices=[('exact', 'Exact'), ('partial', 'Partial'), ('semantic', 'Semantic'), ('none', 'None')], max_length=20)),
                ('matched_text', models.TextField(blank=True, null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity_weight', models.FloatField(default=0.0)),
                ('leakage_risk', models.FloatField(default=0.0)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelresponse')),
            ],
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prompttemplate'),
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensitiverecord'),
        ),
    ]
