# Generated by Django 6.0.3 on 2026-03-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experiment_use_guardshield_alter_experiment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_leak', models.BooleanField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.modelresponse')),
            ],
        ),
    ]
