# Generated by Django 6.0.3 on 2026-03-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mlpredictionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedprompt',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prompttemplate'),
        ),
    ]
