# Generated by Django 6.0.3 on 2026-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_generatedprompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedprompt',
            name='attack_strategy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedprompt',
            name='is_adversarial',
            field=models.BooleanField(default=False),
        ),
    ]
